import type { Category, Product, Restaurant } from "@/types";

export const RESTAURANT: Restaurant = {
  id: "r-cafe-mesa",
  slug: "cafe-mesa",
  name: "Café Mesa",
  tagline: "Café de especialidad y cocina honesta",
  currency: "HNL",
  tables: [
    { id: "t-1", number: 1, qrToken: "tk-mesa-1" },
    { id: "t-2", number: 2, qrToken: "tk-mesa-2" },
    { id: "t-3", number: 3, qrToken: "tk-mesa-3" },
    { id: "t-4", number: 4, qrToken: "tk-mesa-4" },
    { id: "t-5", number: 5, qrToken: "tk-mesa-5" },
    { id: "t-6", number: 6, qrToken: "tk-mesa-6" },
    { id: "t-7", number: 7, qrToken: "tk-mesa-7" },
    { id: "t-8", number: 8, qrToken: "tk-mesa-8" },
  ],
};

export const CATEGORIES: readonly Category[] = [
  { id: "c-cafes", slug: "cafes", name: "Cafés", sortOrder: 1 },
  { id: "c-desayunos", slug: "desayunos", name: "Desayunos", sortOrder: 2 },
  { id: "c-almuerzos", slug: "almuerzos", name: "Almuerzos", sortOrder: 3 },
  { id: "c-postres", slug: "postres", name: "Postres", sortOrder: 4 },
];

export const PRODUCTS: readonly Product[] = [
  {
    id: "p-espresso",
    categoryId: "c-cafes",
    name: "Espresso",
    description: "Doble shot, 30 ml. Intenso y aromático.",
    price: 35,
    available: true,
    emoji: "☕",
  },
  {
    id: "p-latte",
    categoryId: "c-cafes",
    name: "Latte",
    description: "Espresso con leche vaporizada, arte latte.",
    price: 55,
    available: true,
    emoji: "🥛",
  },
  {
    id: "p-capuccino",
    categoryId: "c-cafes",
    name: "Cappuccino",
    description: "Espresso, leche y espuma cremosa, 200 ml.",
    price: 50,
    available: true,
    emoji: "☕",
  },
  {
    id: "p-americano",
    categoryId: "c-cafes",
    name: "Café americano",
    description: "Espresso largo con agua caliente, 240 ml.",
    price: 30,
    available: true,
    emoji: "☕",
  },
  {
    id: "p-baleada-sencilla",
    categoryId: "c-desayunos",
    name: "Baleada sencilla",
    description: "Tortilla de harina, frijoles, mantequilla y queso.",
    price: 25,
    available: true,
    emoji: "🌯",
  },
  {
    id: "p-baleada-todo",
    categoryId: "c-desayunos",
    name: "Baleada con todo",
    description: "Frijoles, mantequilla, queso, huevo, aguacate y carne.",
    price: 60,
    available: true,
    emoji: "🌯",
  },
  {
    id: "p-tostadas-francesas",
    categoryId: "c-desayunos",
    name: "Tostadas francesas",
    description: "Pan brioche, miel de maple, frutas de temporada.",
    price: 90,
    available: true,
    emoji: "🍞",
  },
  {
    id: "p-pollo-papas",
    categoryId: "c-almuerzos",
    name: "Pollo con papas",
    description: "Pechuga a la plancha, papas rústicas y ensalada.",
    price: 130,
    available: true,
    emoji: "🍗",
  },
  {
    id: "p-pasta-dia",
    categoryId: "c-almuerzos",
    name: "Pasta del día",
    description: "Consultá con tu mesero la receta de hoy.",
    price: 120,
    available: true,
    emoji: "🍝",
  },
  {
    id: "p-burger-mesa",
    categoryId: "c-almuerzos",
    name: "Hamburguesa Mesa",
    description: "Carne 200 g, queso cheddar, tocino, papas hechas en casa.",
    price: 150,
    available: true,
    emoji: "🍔",
  },
  {
    id: "p-cheesecake",
    categoryId: "c-postres",
    name: "Cheesecake de fresa",
    description: "Base de galleta, queso crema y coulis de fresa.",
    price: 75,
    available: true,
    emoji: "🍰",
  },
  {
    id: "p-brownie",
    categoryId: "c-postres",
    name: "Brownie con helado",
    description: "Brownie tibio de chocolate con helado de vainilla.",
    price: 70,
    available: true,
    emoji: "🍫",
  },
];
